spring:
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: client-id
            client-secret: client-secret
            redirect-uri: http://localhost:8080/login/oauth2/code/github

  cassandra:
    keyspace-name: main
    username: username
    password: password
    schema-action: recreate-drop-unused
    request:
      timeout: 10s
    connection:
      connect-timeout: 10s
      init-query-timeout: 10s
  main:
    allow-circular-references: true

astra:
  db:
    id: id
    region: us-east-2
    keyspace: main
    application.token: Astra application token

datastax.astra:
  secure-connect-bundle: path-to-secure-bundle


logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.security.oauth2.client: DEBUG
    org.springframework.security.oauth2.core: DEBUG
    org.springframework.web: DEBUG
    com:
      datastax: DEBUG


